[tool.poetry]
name = "proyecto-grado"
version = "0.1.0"
description = ""
authors = ["Facundo Spira <facundospira@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
PuLP = "^2.9.0"
pandas = "^2.2.3"
pyyaml = "^6.0.2"
matplotlib = "^3.10.1"
seaborn = "^0.13.2"
fastapi = "^0.115.0"
uvicorn = "^0.34.0"
python-multipart = "^0.0.20"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
httpx = "^0.28.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
